ARG BASE_IMAGE=pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
FROM ${BASE_IMAGE}

RUN apt update && apt install -y git

WORKDIR /work

RUN git clone https://github.com/826568389/GRPO-R1 && \
    cd ./GRPO-R1 && \
    pip install -r requirements.txt

