# DeepSpeed ZeRO-3 配置
compute_environment: LOCAL_MACHINE  # 计算环境设置
debug: false                       # 是否开启调试模式
deepspeed_config:
  deepspeed_multinode_launcher: standard  # 多节点启动器类型
  offload_optimizer_device: none          # 优化器卸载设备，none表示不卸载
  offload_param_device: none              # 参数卸载设备，none表示不卸载
  zero3_init_flag: true                   # 是否启用ZeRO-3初始化
  zero3_save_16bit_model: true           # 保存16位精度模型
  zero_stage: 3                          # ZeRO优化阶段，3为最高级别

# 分布式训练设置
distributed_type: DEEPSPEED      # 分布式训练类型
downcast_bf16: 'no'             # 是否降级为bf16精度
machine_rank: 0                  # 机器排名，单机为0
main_training_function: main     # 主训练函数名
mixed_precision: bf16            # 混合精度训练设置
num_machines: 1                  # 机器数量
num_processes: 3                 # 进程数量（GPU数量）
rdzv_backend: static            # 集合点后端类型
same_network: true              # 是否在同一网络中
tpu_env: []                     # TPU环境设置
tpu_use_cluster: false          # 是否使用TPU集群
tpu_use_sudo: false             # 是否使用sudo运行TPU命令
use_cpu: false                  # 是否使用CPU训练
